### ISSUE TITLE
Demos does not work

### ISSUE THREAD

**Issue by algida** [thinkpixellab/bot#1]
After run WPF4 demo and choose whatever in menu it shows exception "Must use the rewriter when using Contract.Requies<TException>"

**Comment by kevmoo** [comment]
I'm using CodeContracts code in the BOT. I just updated things in 353dece6484316bfbe70b835b7bd0875019d1f48 to hopefully disable contracts clauses when they are not installed.

Please let me know if you keep seeing this.

Thanks!

**Comment by algida** [comment]
Hi still same

**Comment by kevmoo** [comment]
Do you see the error when you run?
Does it happen before the app loads or once you click on a demo?
Have you done a complete clean and rebuild?

Thanks for working through this with me...

**Comment by algida** [comment]
grr, sry, after cleanup it works, I did rebuild only and it does not work. Thank you

**Comment by algida** [comment]
Oh no, only some demos works

**Comment by kevmoo** [comment]
1) Could you give me an example of a demo that does work and one that doesn't?
2) Could you try building release mode and running without the debugger? Do you get errors?

**Comment by algida** [comment]
ref Issue2
