### ISSUE TITLE
Again as Issue 1

### ISSUE THREAD

**Issue by algida** [thinkpixellab/bot#2]
After run WPF4 demo and choose whatever in menu it shows exception "Must use the rewriter when using Contract.Requies"

It works only on some demos.
These does not work:
Animating Title Panel
Graphs 
Org Tree
Set game
Treemap panel
Zap controler

**Comment by algida** [comment]
Release/Debug is same in point of view of errors (sry for my English)

**Comment by kevmoo** [comment]
Removed uses of Contract.Requires<T>

For some (crazy) reason, these are not set to conditionally compile -> causes runtime errors for people who build without contracts tools installed
Closed by 76f325ffecefc409bf1e0d1c7937fc6b2e675635. Closed by 76f325ffecefc409bf1e0d1c7937fc6b2e675635.

**Comment by algida** [comment]
Great working now.
