### ISSUE TITLE
InfoTextBox: Selection is not cropped

### ISSUE THREAD

**Issue by averkiev** [thinkpixellab/bot#3]
Hi,
I'm planing with the InfoTextBox control and I've noticed and issue. 

I picture would say a thousand words, so please take a look:
http://yurysweb.com/tmp/InfoTextBox_bug.jpg

As you can see from the screenshot, the selection doesn't get cropped.

Thanks,
Yury

**Comment by kevmoo** [comment]
Ooo...good bug.
