### ISSUE TITLE
Invalid .sln files

### ISSUE THREAD

**Issue by wadells** [thinkpixellab/bot#9]
Since the great file move around, Demo_SL4.sln, Demo_WP7.sln, and Demo_WPF4.sln still have the old folder names in their project references, though Demo_All.sln properly reflects the new structure.  The other solutions need to be updated to run in VS straight out of the box.  I'd fix it myself and submit a pull, but at the moment I'm on a work computer without git. :(

**Comment by wadells** [comment]
Or just remove the offending files.  That works as well.

**Comment by kevmoo** [comment]
Happy to help! :-)

...and you can just right-click and 'unload' a solution folder for the platforms you don't care about.
